apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: dev
  subsets:
    - name: v1
      labels:
        version: v1
    - name: dev
      labels:
        version: dev
