apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: productpage-dev-route
spec:
  to:
    kind: Service
    name: productpage-dev
    weight: 100
  path: /WebApp
  port:
    targetPort: "tcp-8080"
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
