kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata: 
  name: productpage-dev 
  namespace: istio-servicemesh1   
  labels:
    kiali_wizard: request_routing
spec: 
  hosts:
    - '*'  
  gateways:   
    - istio-servicemesh1/productpage-dev-gateway
  http:   
    - route:
        - destination:   
            host: productpage-dev.istio-servicemesh1.svc.cluster.local
            subset: dev
          weight: 100
