apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage-1.1-SNAPSHOT
spec:
  hosts:
    - productpage
  http:
    - route:
        - destination:
            host: productpage
            subset: $(SERVICE_VERSION)
          weight: "90"
