# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: productpage-dev
# spec:
#   hosts:
#     - productpage
#   http:
#     - route:
#         - destination:
#             host: productpage
#             subset: dev
#           weight: 100



kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  namespace: istio-servicemesh1
  name: productpage-dev
  labels:
    kiali_wizard: request_routing
  annotations: ~
spec:
  host: productpage-dev.istio-servicemesh1.svc.cluster.local
  subsets:
    - name: dev
      labels:
        version: dev
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      consistentHash: ~
