apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:4370fb8b46e8fab0cfcd27db88c79cb0225cd88011e79688b8c2ee330bed3b67
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:ff906a0b0f90baec595cee3336ab79ce25e0ae9f
