apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:9fdd8694691f8c03b8483dd35a789d9d2ba69c72bf47ff3ac1fd39d1cfabd55c
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:test
