apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:279a8713fbfec6317fc76ca5466817497181f0cf2a996e37341c802ae2647032
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:054d22d666dedd37a308cc89ff9b049522c12d51
