apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:6c3cb48c02dd0339bbdb43ebbf1c22bbe52fc72296ffba781a0ac3816d5c3cd1
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:054d22d666dedd37a308cc89ff9b049522c12d51
